
// This file has been generated by the GUI designer. Do not modify.
namespace catoolgui
{
	public partial class createNewRequest
	{
		private global::Gtk.Table table1;
		
		private global::Gtk.HButtonBox hbuttonbox4;
		
		private global::Gtk.Button OKButtonReq;
		
		private global::Gtk.Button CancelButtonReq;
		
		private global::Gtk.Label keyBoxLabel;
		
		private global::Gtk.Label keyLabel;
		
		private global::Gtk.Label KeyLabelConf;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ComboBox reqCipherBox;
		
		private global::Gtk.Entry reqCommon;
		
		private global::Gtk.Entry reqCountry;
		
		private global::Gtk.Entry reqDays;
		
		private global::Gtk.Entry reqeMail;
		
		private global::Gtk.Entry reqKeyPass;
		
		private global::Gtk.Entry reqKeyPassConf;
		
		private global::Gtk.ComboBox reqKeySizeBox;
		
		private global::Gtk.Entry reqLocality;
		
		private global::Gtk.Entry reqName;
		
		private global::Gtk.Entry reqOrga;
		
		private global::Gtk.Entry reqOrgaUnit;
		
		private global::Gtk.Entry reqState;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget catoolgui.createNewRequest
			this.CanDefault = true;
			this.CanFocus = true;
			this.Name = "catoolgui.createNewRequest";
			this.Title = global::Mono.Unix.Catalog.GetString ("Certificate Creation - Step 1: Request");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.AllowShrink = true;
			// Container child catoolgui.createNewRequest.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(16)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.hbuttonbox4 = new global::Gtk.HButtonBox ();
			this.hbuttonbox4.Name = "hbuttonbox4";
			this.hbuttonbox4.Spacing = 83;
			this.hbuttonbox4.BorderWidth = ((uint)(3));
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.OKButtonReq = new global::Gtk.Button ();
			this.OKButtonReq.CanFocus = true;
			this.OKButtonReq.Name = "OKButtonReq";
			this.OKButtonReq.UseStock = true;
			this.OKButtonReq.UseUnderline = true;
			this.OKButtonReq.Label = "gtk-ok";
			this.hbuttonbox4.Add (this.OKButtonReq);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.OKButtonReq]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButtonReq = new global::Gtk.Button ();
			this.CancelButtonReq.CanFocus = true;
			this.CancelButtonReq.Name = "CancelButtonReq";
			this.CancelButtonReq.UseStock = true;
			this.CancelButtonReq.UseUnderline = true;
			this.CancelButtonReq.Label = "gtk-cancel";
			this.hbuttonbox4.Add (this.CancelButtonReq);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.CancelButtonReq]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.table1.Add (this.hbuttonbox4);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbuttonbox4]));
			w3.TopAttach = ((uint)(15));
			w3.BottomAttach = ((uint)(16));
			w3.XOptions = ((global::Gtk.AttachOptions)(0));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.keyBoxLabel = new global::Gtk.Label ();
			this.keyBoxLabel.Name = "keyBoxLabel";
			this.keyBoxLabel.Xalign = 0F;
			this.keyBoxLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Keylength");
			this.table1.Add (this.keyBoxLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.keyBoxLabel]));
			w4.TopAttach = ((uint)(13));
			w4.BottomAttach = ((uint)(14));
			w4.XPadding = ((uint)(10));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.keyLabel = new global::Gtk.Label ();
			this.keyLabel.Name = "keyLabel";
			this.keyLabel.Xalign = 0F;
			this.keyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Key Password");
			this.table1.Add (this.keyLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.keyLabel]));
			w5.TopAttach = ((uint)(9));
			w5.BottomAttach = ((uint)(10));
			w5.XPadding = ((uint)(10));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.KeyLabelConf = new global::Gtk.Label ();
			this.KeyLabelConf.Name = "KeyLabelConf";
			this.KeyLabelConf.Xalign = 0F;
			this.KeyLabelConf.LabelProp = global::Mono.Unix.Catalog.GetString ("KeyPassword Confirmation");
			this.table1.Add (this.KeyLabelConf);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.KeyLabelConf]));
			w6.TopAttach = ((uint)(10));
			w6.BottomAttach = ((uint)(11));
			w6.XPadding = ((uint)(10));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("State / Province Name");
			this.table1.Add (this.label16);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label16]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XPadding = ((uint)(10));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 0F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Locality Name (optional)");
			this.table1.Add (this.label17);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label17]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.XPadding = ((uint)(10));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Organization Name");
			this.table1.Add (this.label18);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label18]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.XPadding = ((uint)(10));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xalign = 0F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Organization Unit Name (optional)");
			this.table1.Add (this.label19);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label19]));
			w10.TopAttach = ((uint)(7));
			w10.BottomAttach = ((uint)(8));
			w10.XPadding = ((uint)(10));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xpad = 10;
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name (for storage)");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xalign = 0F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("eMail-Address (optional)");
			this.table1.Add (this.label20);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.label20]));
			w12.TopAttach = ((uint)(8));
			w12.BottomAttach = ((uint)(9));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xalign = 0F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Valid (Days)");
			this.table1.Add (this.label21);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.label21]));
			w13.TopAttach = ((uint)(12));
			w13.BottomAttach = ((uint)(13));
			w13.XPadding = ((uint)(10));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xalign = 0F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Cipher Algorithm");
			this.table1.Add (this.label23);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.label23]));
			w14.TopAttach = ((uint)(14));
			w14.BottomAttach = ((uint)(15));
			w14.XPadding = ((uint)(10));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Country Name");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.XPadding = ((uint)(10));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Common Name");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XPadding = ((uint)(10));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Recommended Settings</b>");
			this.label5.UseMarkup = true;
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w17.TopAttach = ((uint)(11));
			w17.BottomAttach = ((uint)(12));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XPadding = ((uint)(10));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Subject Information</b>");
			this.label6.UseMarkup = true;
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqCipherBox = global::Gtk.ComboBox.NewText ();
			this.reqCipherBox.AppendText (global::Mono.Unix.Catalog.GetString ("aes192"));
			this.reqCipherBox.AppendText (global::Mono.Unix.Catalog.GetString ("aes256"));
			this.reqCipherBox.Name = "reqCipherBox";
			this.reqCipherBox.Active = 0;
			this.table1.Add (this.reqCipherBox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqCipherBox]));
			w19.TopAttach = ((uint)(14));
			w19.BottomAttach = ((uint)(15));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XPadding = ((uint)(10));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqCommon = new global::Gtk.Entry ();
			this.reqCommon.CanFocus = true;
			this.reqCommon.Name = "reqCommon";
			this.reqCommon.IsEditable = true;
			this.reqCommon.InvisibleChar = '•';
			this.table1.Add (this.reqCommon);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqCommon]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XPadding = ((uint)(10));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqCountry = new global::Gtk.Entry ();
			this.reqCountry.CanFocus = true;
			this.reqCountry.Name = "reqCountry";
			this.reqCountry.IsEditable = true;
			this.reqCountry.MaxLength = 2;
			this.reqCountry.InvisibleChar = '•';
			this.table1.Add (this.reqCountry);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqCountry]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XPadding = ((uint)(10));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqDays = new global::Gtk.Entry ();
			this.reqDays.CanFocus = true;
			this.reqDays.Name = "reqDays";
			this.reqDays.Text = global::Mono.Unix.Catalog.GetString ("365");
			this.reqDays.IsEditable = true;
			this.reqDays.InvisibleChar = '•';
			this.table1.Add (this.reqDays);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqDays]));
			w22.TopAttach = ((uint)(12));
			w22.BottomAttach = ((uint)(13));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XPadding = ((uint)(10));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqeMail = new global::Gtk.Entry ();
			this.reqeMail.CanFocus = true;
			this.reqeMail.Name = "reqeMail";
			this.reqeMail.IsEditable = true;
			this.reqeMail.InvisibleChar = '•';
			this.table1.Add (this.reqeMail);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqeMail]));
			w23.TopAttach = ((uint)(8));
			w23.BottomAttach = ((uint)(9));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XPadding = ((uint)(10));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqKeyPass = new global::Gtk.Entry ();
			this.reqKeyPass.CanFocus = true;
			this.reqKeyPass.Name = "reqKeyPass";
			this.reqKeyPass.IsEditable = true;
			this.reqKeyPass.Visibility = false;
			this.reqKeyPass.InvisibleChar = '•';
			this.table1.Add (this.reqKeyPass);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqKeyPass]));
			w24.TopAttach = ((uint)(9));
			w24.BottomAttach = ((uint)(10));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XPadding = ((uint)(10));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqKeyPassConf = new global::Gtk.Entry ();
			this.reqKeyPassConf.CanFocus = true;
			this.reqKeyPassConf.Name = "reqKeyPassConf";
			this.reqKeyPassConf.IsEditable = true;
			this.reqKeyPassConf.Visibility = false;
			this.reqKeyPassConf.InvisibleChar = '•';
			this.table1.Add (this.reqKeyPassConf);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqKeyPassConf]));
			w25.TopAttach = ((uint)(10));
			w25.BottomAttach = ((uint)(11));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XPadding = ((uint)(10));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqKeySizeBox = global::Gtk.ComboBox.NewText ();
			this.reqKeySizeBox.AppendText (global::Mono.Unix.Catalog.GetString ("2048"));
			this.reqKeySizeBox.AppendText (global::Mono.Unix.Catalog.GetString ("4096"));
			this.reqKeySizeBox.Name = "reqKeySizeBox";
			this.reqKeySizeBox.Active = 0;
			this.table1.Add (this.reqKeySizeBox);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqKeySizeBox]));
			w26.TopAttach = ((uint)(13));
			w26.BottomAttach = ((uint)(14));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XPadding = ((uint)(10));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqLocality = new global::Gtk.Entry ();
			this.reqLocality.CanFocus = true;
			this.reqLocality.Name = "reqLocality";
			this.reqLocality.IsEditable = true;
			this.reqLocality.InvisibleChar = '•';
			this.table1.Add (this.reqLocality);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqLocality]));
			w27.TopAttach = ((uint)(5));
			w27.BottomAttach = ((uint)(6));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XPadding = ((uint)(10));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqName = new global::Gtk.Entry ();
			this.reqName.CanFocus = true;
			this.reqName.Name = "reqName";
			this.reqName.IsEditable = true;
			this.reqName.InvisibleChar = '•';
			this.table1.Add (this.reqName);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqName]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XPadding = ((uint)(10));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqOrga = new global::Gtk.Entry ();
			this.reqOrga.CanFocus = true;
			this.reqOrga.Name = "reqOrga";
			this.reqOrga.IsEditable = true;
			this.reqOrga.InvisibleChar = '•';
			this.table1.Add (this.reqOrga);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqOrga]));
			w29.TopAttach = ((uint)(6));
			w29.BottomAttach = ((uint)(7));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XPadding = ((uint)(10));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqOrgaUnit = new global::Gtk.Entry ();
			this.reqOrgaUnit.CanFocus = true;
			this.reqOrgaUnit.Name = "reqOrgaUnit";
			this.reqOrgaUnit.IsEditable = true;
			this.reqOrgaUnit.InvisibleChar = '•';
			this.table1.Add (this.reqOrgaUnit);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqOrgaUnit]));
			w30.TopAttach = ((uint)(7));
			w30.BottomAttach = ((uint)(8));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XPadding = ((uint)(10));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reqState = new global::Gtk.Entry ();
			this.reqState.CanFocus = true;
			this.reqState.Name = "reqState";
			this.reqState.IsEditable = true;
			this.reqState.InvisibleChar = '•';
			this.table1.Add (this.reqState);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.reqState]));
			w31.TopAttach = ((uint)(4));
			w31.BottomAttach = ((uint)(5));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.XPadding = ((uint)(10));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 452;
			this.DefaultHeight = 515;
			this.HasDefault = true;
			this.Show ();
			this.OKButtonReq.Clicked += new global::System.EventHandler (this.OnOKButtonReqClicked);
			this.CancelButtonReq.Clicked += new global::System.EventHandler (this.OnCancelButtonReqClicked);
		}
	}
}
