
// This file has been generated by the GUI designer. Do not modify.
namespace compactCA
{
	public partial class crlExt
	{
		private global::Gtk.Table table2;
		
		private global::Gtk.Entry crlDays;
		
		private global::Gtk.Label crlLabel;
		
		private global::Gtk.Entry crlURIEntry;
		
		private global::Gtk.Button crlWinClose;
		
		private global::Gtk.HButtonBox hbuttonbox2;
		
		private global::Gtk.Button crlAdd;
		
		private global::Gtk.Button crlDel;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget catoolgui.crlExt
			this.Name = "catoolgui.crlExt";
			this.Title = global::Mono.Unix.Catalog.GetString ("CRL Extension");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child catoolgui.crlExt.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.crlDays = new global::Gtk.Entry ();
			this.crlDays.CanFocus = true;
			this.crlDays.Name = "crlDays";
			this.crlDays.Text = global::Mono.Unix.Catalog.GetString ("30");
			this.crlDays.IsEditable = true;
			this.crlDays.InvisibleChar = '•';
			this.table2.Add (this.crlDays);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.crlDays]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XPadding = ((uint)(10));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.crlLabel = new global::Gtk.Label ();
			this.crlLabel.Name = "crlLabel";
			this.crlLabel.UseMarkup = true;
			this.table2.Add (this.crlLabel);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.crlLabel]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XPadding = ((uint)(10));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.crlURIEntry = new global::Gtk.Entry ();
			this.crlURIEntry.CanFocus = true;
			this.crlURIEntry.Name = "crlURIEntry";
			this.crlURIEntry.IsEditable = true;
			this.crlURIEntry.InvisibleChar = '•';
			this.table2.Add (this.crlURIEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.crlURIEntry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XPadding = ((uint)(10));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.crlWinClose = new global::Gtk.Button ();
			this.crlWinClose.CanFocus = true;
			this.crlWinClose.Name = "crlWinClose";
			this.crlWinClose.UseUnderline = true;
			this.crlWinClose.Label = global::Mono.Unix.Catalog.GetString ("Close");
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.crlWinClose.Image = w4;
			this.table2.Add (this.crlWinClose);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.crlWinClose]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XPadding = ((uint)(10));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.crlAdd = new global::Gtk.Button ();
			this.crlAdd.CanFocus = true;
			this.crlAdd.Name = "crlAdd";
			this.crlAdd.UseUnderline = true;
			this.crlAdd.Label = global::Mono.Unix.Catalog.GetString ("Add");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.crlAdd.Image = w6;
			this.hbuttonbox2.Add (this.crlAdd);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.crlAdd]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.crlDel = new global::Gtk.Button ();
			this.crlDel.Sensitive = false;
			this.crlDel.CanFocus = true;
			this.crlDel.Name = "crlDel";
			this.crlDel.UseUnderline = true;
			this.crlDel.Label = global::Mono.Unix.Catalog.GetString ("Delete");
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			this.crlDel.Image = w8;
			this.hbuttonbox2.Add (this.crlDel);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.crlDel]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table2.Add (this.hbuttonbox2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbuttonbox2]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Set URL for CRL</b>");
			this.label1.UseMarkup = true;
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w11.XPadding = ((uint)(10));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Set CRL valid period(Days)</b>");
			this.label3.UseMarkup = true;
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XPadding = ((uint)(10));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 549;
			this.DefaultHeight = 119;
			this.Show ();
			this.crlAdd.Clicked += new global::System.EventHandler (this.OnCrlAddClicked);
			this.crlDel.Clicked += new global::System.EventHandler (this.OnCrlDelClicked);
			this.crlWinClose.Clicked += new global::System.EventHandler (this.OnCrlWinCloseClicked);
		}
	}
}
